### ISSUE TITLE
Card Detect polarity

### ISSUE THREAD

**Issue by andy-shev** [Joel2B/Intel-Edison-Breakout-with-micro-sd-card-slot#1]
It's rather a question. Do you have the Card Detect polarity Active High or Active Low? There is a problem between Intel and SparkFun PCB designs on which they are contradicting each other (Intel uses Active Low, while SparkFun uses Active High). Interestingly that the software **luckily** works in both cases, that drives me crazy.

**Comment by Joel2B** [comment]
I think the card detection polarity is active high, I based it on the sparkfun design, but I don't use the same slot so I don't know if it behaves the same way as the one I used.
without card, the CD pin gives 1.8v, and with card, it gives 0v.
I used jubilinux and these are the states of the pins:
with card
![image](https://user-images.githubusercontent.com/58922368/135734431-6d23a7e0-2245-4759-9463-23d4c696d9af.png)
without card
![image](https://user-images.githubusercontent.com/58922368/135734435-8284c972-b67c-4fab-b21b-be58cd00d21c.png)
I haven't tried more distros or updated the u-boot, I think it was lucky it worked.

**Comment by andy-shev** [comment]
> I think the card detection polarity is active high, I based it on the sparkfun design,

SparkFun is using Active High, but it means the opposite to what you descibe below.

> but I don't use the same slot so I don't know if it behaves the same way as the one I used. without card, the CD pin gives 1.8v, and with card, it gives 0v.

It's Active Low and it's good design!

P.S. In case you wonder there is an ongoing discussion: https://github.com/edison-fw/meta-intel-edison/issues/135
